# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-27 09:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('cpu_cores', models.IntegerField(default=2)),
                ('memory_size', models.FloatField(default=4)),
                ('disk_size', models.FloatField(default=40)),
                ('mysql_release', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('var_name', models.CharField(default='', max_length=64, verbose_name='MySQL参数(variable)名')),
                ('var_value', models.CharField(default='', max_length=64, verbose_name='MySQL参数(variable)值')),
                ('oltp_type', models.CharField(choices=[('delete', 'oltp_delete'), ('insert', 'oltp_insert'), ('point_select', 'oltp_point_select'), ('read_only', 'oltp_read_only'), ('read_write', 'oltp_read_write'), ('update_index', 'oltp_update_index'), ('write_only', 'oltp_write_only')], max_length=64, verbose_name='OLTP 测试类型')),
                ('threads', models.PositiveIntegerField(default=1, verbose_name='并发线程数量')),
                ('qps', models.FloatField(default=0, verbose_name='qps')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='mysqlz.Host')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='host',
            unique_together=set([('name', 'mysql_release')]),
        ),
        migrations.AlterUniqueTogether(
            name='mark',
            unique_together=set([('host', 'var_name', 'var_value', 'oltp_type', 'threads')]),
        ),
    ]
